### ISSUE TITLE
Dployment fails is a cluster called cluedin-aks already exists

### ISSUE THREAD

**Issue by andrew-hardy** [CluedIn-io/AzureDeploy#3]

**Comment by andrew-hardy** [comment]
{
    "status": "Failed",
    "error": {
        "code": "InvalidTemplateDeployment",
        "message": "The template deployment 'cluedinmds3-aks' is not valid according to the validation procedure. The tracking id is '2688a797-d029-4312-98c9-dd0910f354bc'. See inner errors for details.",
        "details": [
            {
                "code": "NodeResourceGroupAlreadyExists",
                "message": "Provisioning of resource(s) for container service cluedin-aks in resource group hardyan-mds3-rg failed. Message: {\n  \"code\": \"NodeResourceGroupAlreadyExists\",\n  \"message\": \"Node resource group 'cluedin-aks-nodepool' under subscription '3fa2142d-0d79-4df1-9ea0-51b64ad6768d' already exists, please provide a new one.\"\n }. Details: "
            }
        ]
    }
}

**Comment by stephenpope** [comment]
Moved to Azure Dev Ops 984
