### ISSUE TITLE
Create AKS nodes to match documentation

### ISSUE THREAD

**Issue by stephenpope** [CluedIn-io/AzureDeploy#6]
Generic 1 x D8
Data = 3 x D8
Processing = 1 x F16

**Comment by stephenpope** [comment]
Closed by Azure Dev Ops : 982

**Comment by nathanguk** [comment]
The documentation [here](https://documentation.cluedin.net/deployment/kubernetes/deployment#kubernetes-cluster) recomends a slightly different configuration.

Node Pool | VM SKU Type | Amount | Purpose
-- | -- | -- | --
Core Pool | Standard_DS2_v2 | 1 | Kubernetes agent internal processes
Data Pool | Standard_A8_v2 | 2 | Memory Optimized pool for Databases
Processing Pool | Standard_F16s_v2 | 1 | CPU Optimized for Processing workloads
General Pool | Standard_F4s_v2 | 2 | General Purpose nodepool to house CluedIn Microservices
